### PR TITLE
Handle session and custom variable name

### PR DESCRIPTION
**Pull request by kaushalrajbacancy**
- chain can't be set if want to allow custom chain id. Otherwise, it will take the chain id from the initialized SDK only.

## Description

-

## Motivation and Context

-

## How Has This Been Tested?

-
-
-

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by marie-fourier — APPROVED** [review]
LGTM

**Review by arddluma — CHANGES_REQUESTED** [review]
Could you please update example code ?

**Comment by kaushalrajbacancy** [comment]
@arddluma What change does it require? I guess it should be as it is.

**Review by marie-fourier — APPROVED** [review]

**Review by arddluma — APPROVED** [review]
LGTM

**Pull request merged**
